name: COTR_64
model: cotr
# pth: /home/myr/these/datasets
pth: /etudiants/siscol/t/themyr_l/US
# pth: /scratch/lthemyr/US


net_num_pool_op_kernel_sizes: [[1, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2]]
net_conv_kernel_sizes: [[1, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]]

feature_size: 0