name: FINE
model: fine
# pth: /home/myr/these/datasets
# pth: /etudiants/siscol/t/themyr_l/US
pth: /scratch/lthemyr/US


net_num_pool_op_kernel_sizes: [[2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2]]
net_conv_kernel_sizes: [[3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]]

