name: ct_128_final_jz
path: 
  pth: /gpfsscratch/rech/arf/unm89rb/Trusted_v1_Loic/CT_DATA
  im: ${dataset.path.pth}/CTimg_128
  seg2: ${dataset.path.pth}/CTmask_a2_128
  seg3: ${dataset.path.pth}/CTmask_a3_128
  seg23: ${dataset.path.pth}/CTmask_mf_128

im_size: [128,128,128]

len: 39
classes: 1

cv: cv1