name: ct_full_double_jz
path: 
  pth: /gpfsscratch/rech/arf/unm89rb/Trusted_v1_Loic/CT_DATA
  im: ${dataset.path.pth}/CTimg_full
  seg2: ${dataset.path.pth}/CTmask_a2_full
  seg3: ${dataset.path.pth}/CTmask_a3_full
  seg23: ${dataset.path.pth}/CTmask_mf_full

im_size: [128,128,128]

len: 39
classes: 1

cv: cv1