name: US_256
path: 
  # pth: /scratch/lthemyr/US/us_3d_segmentation_dataset_08_03_2022
  # pth: /etudiants/siscol/t/themyr_l/US/us_3d_segmentation_dataset_08_03_2022
  pth: /local/DEEPLEARNING/20220318_US_DATA
  im: ${dataset.path.pth}/USimg_cropped256_npz
  seg: ${dataset.path.pth}/USmask_cropped256_npz
  ori: ${dataset.path.pth}/USmask_cropped

im_size: [256,256,256]

len: 39
split:
  n_train: 31
  n_val: 8
  train: [34,  4, 10,  1, 37, 27,  8, 30,  9, 28,  3, 16,  2, 36, 19, 24,  0, 23, 11, 14, 29, 38,  7, 32, 20, 21, 25, 31, 12, 22,  5]
  val: [18, 17, 33, 26, 15,  6, 35, 13]
classes: 1

cv: cv1