name: us_128_double_jz
path: 
  pth: /gpfsscratch/rech/arf/unm89rb/Trusted_v1_Loic/US_DATA
  im: ${dataset.path.pth}/USimg_128_a
  seg2: ${dataset.path.pth}/USmask_a2_128
  seg3: ${dataset.path.pth}/USmask_a3_128
  seg23: ${dataset.path.pth}/USmask_mf_128

im_size: [128,128,128]

len: 39
classes: 1

cv: cv1