name: CROP_SMALL_CD
dbg: True
gpu: 1
use_gpu: True
only_val: False


optim: adam
lr: 1e-2
weight_decay: 1e-5
epochs: 2000
iter: 0
online_validation: True
eval_step: 1
batch_size: 4
num_workers: 1
crop_size: [128,128,128]
do_clip: True
do_schedul: True
loss: CrossDice # Dice

pth: /etudiants/siscol/t/themyr_l/US

augmentations:
  rotate:
    x_: [-0.5235987755982988, 0.5235987755982988]
    y_: [-0.5235987755982988, 0.5235987755982988]
    z_: [-0.5235987755982988, 0.5235987755982988]
    p_: 0.2
  scale:
    min_: 0.7
    max_: 1.4
    p_: 0.2
  gamma:
    g_: [0.7, 1.5]
    p_: 0.3

inference:
  stride: [1,1,1]

checkpoint:
  save: 1
  load: False
  load_path: ${model.pth}/${model.name}/checkpoint/latest.pt
  path: ${model.pth}/${model.name}/checkpoint