name: Default
dbg: True
gpu: 0
use_gpu: True
only_val: False

lr: 1e-2
weight_decay: 3e-5
epochs: 1000
iter: 250
batch_size: 2
num_workers: 12
crop_size: [64,128,128]
# net_num_pool_op_kernel_sizes: [[1, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2]]
# net_conv_kernel_sizes: [[1, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]]
do_clip: True
do_schedul: True
pth: /etudiants/siscol/t/themyr_l/US


augmentations:
  rotate:
    x_: [-0.5235987755982988, 0.5235987755982988]
    y_: [-0.5235987755982988, 0.5235987755982988]
    z_: [-0.5235987755982988, 0.5235987755982988]
    p_: 0.2
  scale:
    min_: 0.7
    max_: 1.4
    p_: 0.2
  gamma:
    g_: [0.7, 1.5]
    p_: 0.3

inference:
  stride: [0.5, 0.5, 0.5]

checkpoint:
  save: 1
  load: False
  load_path: ${model.pth}/${model.name}/checkpoint/latest.pt
  path: ${model.pth}/${model.name}/checkpoint