defaults:
  - dataset: us
  - model: fine
  - training: default
  - _self_


hydra:
  run:
    dir: outputs/${dataset.name}/${model.name}/${training.name}
  sweep:
    dir: outputs/${dataset.name}/${model.name}
    subdir: ${training.name}:${hydra.job.num}
  verbose: [__main__]


# nnunet: 7.7 s/it