defaults:
  - dataset: us128
  - model: nnunet
  - training: crop128_128_128
  - _self_


hydra:
  run:
    dir: outputs/${dataset.name}/${model.name}/${training.name}
  sweep:
    dir: outputs/${dataset.name}/${model.name}
    subdir: ${training.name}:${hydra.job.num}
  verbose: [__main__]

# 3.41 it/s